export const CATEGORIES = ["geografia", "historia", "ciencia", "arte", "literatura", "matematicas", "cultura", "deportes", "musica", "filosofia"];
export const DIFFICULTIES = ["facil", "media", "dificil"];

export const getRandomQuestion = (category, difficulty) => {
    const filteredQuestions = QUESTIONS.filter((q) => q.category === category && q.difficulty === difficulty);
    if (filteredQuestions.length === 0) {
        return null;
    }
    const randomIndex = Math.floor(Math.random() * filteredQuestions.length);
    return filteredQuestions[randomIndex];
};

export const getRandomDifficulty = () => {
    const randomIndex = Math.floor(Math.random() * DIFFICULTIES.length);
    return DIFFICULTIES[randomIndex];
};

export const getRandomCategory = () => {
    const randomIndex = Math.floor(Math.random() * CATEGORIES.length);
    return CATEGORIES[randomIndex];
};

export const QUESTIONS = [
    {
        id: 1,
        question: "¿Cuál es el río más largo del mundo?",
        options: { A: "Nilo", B: "Amazonas", C: "Yangtsé" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 2,
        question: "¿En qué año llegó el hombre a la Luna por primera vez?",
        options: { A: "1965", B: "1969", C: "1972" },
        correct_answer: "B",
        difficulty: "facil",
        category: "historia",
    },
    {
        id: 3,
        question: "¿Cuál es el elemento químico con símbolo 'O'?",
        options: { A: "Oro", B: "Osmio", C: "Oxígeno" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 4,
        question: "¿Quién pintó 'La última cena'?",
        options: { A: "Miguel Ángel", B: "Pablo Picasso", C: "Leonardo da Vinci" },
        correct_answer: "C",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 5,
        question: "¿Cuál es la capital de Australia?",
        options: { A: "Sídney", B: "Melbourne", C: "Canberra" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 6,
        question: "¿En qué continente se encuentra Egipto?",
        options: { A: "Asia", B: "África", C: "Europa" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 7,
        question: "¿Cuál es el planeta más grande del sistema solar?",
        options: { A: "Tierra", B: "Saturno", C: "Júpiter" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 8,
        question: "¿Quién escribió 'Cien años de soledad'?",
        options: { A: "Pablo Neruda", B: "Gabriel García Márquez", C: "Mario Vargas Llosa" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 9,
        question: "¿Cuántos lados tiene un heptágono?",
        options: { A: "5", B: "6", C: "7" },
        correct_answer: "C",
        difficulty: "facil",
        category: "matematicas",
    },
    {
        id: 10,
        question: "¿Qué idioma es el más hablado del mundo como lengua nativa?",
        options: { A: "Inglés", B: "Hindi", C: "Chino mandarín" },
        correct_answer: "C",
        difficulty: "media",
        category: "cultura",
    },
    {
        id: 11,
        question: "¿Cuál es el océano más grande del mundo?",
        options: { A: "Atlántico", B: "Índico", C: "Pacífico" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 12,
        question: "¿Quién escribió 'La Odisea'?",
        options: { A: "Homero", B: "Sófocles", C: "Virgilio" },
        correct_answer: "A",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 13,
        question: "¿Cuál es el símbolo químico del carbono?",
        options: { A: "Ca", B: "C", C: "Co" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 14,
        question: "¿En qué país se originó la Revolución Industrial?",
        options: { A: "Francia", B: "Alemania", C: "Inglaterra" },
        correct_answer: "C",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 15,
        question: "¿Cuántos continentes hay en el mundo?",
        options: { A: "5", B: "6", C: "7" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 16,
        question: "¿Quién pintó 'La noche estrellada'?",
        options: { A: "Claude Monet", B: "Vincent van Gogh", C: "Pablo Picasso" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 17,
        question: "¿Cuál es el planeta más pequeño del sistema solar?",
        options: { A: "Marte", B: "Mercurio", C: "Venus" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 18,
        question: "¿Qué país es conocido como 'El país del sol naciente'?",
        options: { A: "China", B: "Japón", C: "Corea del Sur" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 19,
        question: "¿Quién fue el primer presidente de Estados Unidos?",
        options: { A: "Thomas Jefferson", B: "Abraham Lincoln", C: "George Washington" },
        correct_answer: "C",
        difficulty: "facil",
        category: "historia",
    },
    {
        id: 20,
        question: "¿Cuál es el resultado de 9 x 8?",
        options: { A: "64", B: "72", C: "81" },
        correct_answer: "B",
        difficulty: "facil",
        category: "matematicas",
    },
    {
        id: 21,
        question: "¿Qué escritor creó el personaje de Harry Potter?",
        options: { A: "J.R.R. Tolkien", B: "J.K. Rowling", C: "Roald Dahl" },
        correct_answer: "B",
        difficulty: "facil",
        category: "literatura",
    },
    {
        id: 22,
        question: "¿Cuál es el río más caudaloso del mundo?",
        options: { A: "Nilo", B: "Amazonas", C: "Misisipi" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 23,
        question: "¿Qué órgano bombea la sangre en el cuerpo humano?",
        options: { A: "Pulmón", B: "Hígado", C: "Corazón" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 24,
        question: "¿En qué año comenzó la Primera Guerra Mundial?",
        options: { A: "1912", B: "1914", C: "1918" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 25,
        question: "¿Quién compuso 'La flauta mágica'?",
        options: { A: "Beethoven", B: "Mozart", C: "Bach" },
        correct_answer: "B",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 26,
        question: "¿Cuál es el desierto más grande del mundo?",
        options: { A: "Sahara", B: "Gobi", C: "Antártico" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 27,
        question: "¿Qué filósofo griego fue condenado a beber cicuta?",
        options: { A: "Platón", B: "Aristóteles", C: "Sócrates" },
        correct_answer: "C",
        difficulty: "media",
        category: "filosofia",
    },
    {
        id: 28,
        question: "¿Cuál es el hueso más largo del cuerpo humano?",
        options: { A: "Fémur", B: "Tibia", C: "Húmero" },
        correct_answer: "A",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 29,
        question: "¿Qué país ganó la Copa Mundial de Fútbol de 2014?",
        options: { A: "Argentina", B: "Alemania", C: "Brasil" },
        correct_answer: "B",
        difficulty: "media",
        category: "deportes",
    },
    {
        id: 30,
        question: "¿Cuál es la capital de Egipto?",
        options: { A: "Alejandría", B: "El Cairo", C: "Luxor" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 31,
        question: "¿Qué científico formuló la teoría de la relatividad?",
        options: { A: "Isaac Newton", B: "Albert Einstein", C: "Nikola Tesla" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 32,
        question: "¿Quién escribió 'Romeo y Julieta'?",
        options: { A: "William Shakespeare", B: "Charles Dickens", C: "Jane Austen" },
        correct_answer: "A",
        difficulty: "facil",
        category: "literatura",
    },
    {
        id: 33,
        question: "¿Cuál es el país más poblado de África?",
        options: { A: "Egipto", B: "Nigeria", C: "Sudáfrica" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 34,
        question: "¿Qué emperador romano legalizó el cristianismo?",
        options: { A: "Nerón", B: "Constantino", C: "Julio César" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 35,
        question: "¿Cuál es el metal más conductor de electricidad?",
        options: { A: "Oro", B: "Cobre", C: "Plata" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 36,
        question: "¿Quién pintó 'Guernica'?",
        options: { A: "Salvador Dalí", B: "Pablo Picasso", C: "Joan Miró" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 37,
        question: "¿Cuál es la montaña más alta del mundo?",
        options: { A: "K2", B: "Everest", C: "Kilimanjaro" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 38,
        question: "¿Qué instrumento mide los terremotos?",
        options: { A: "Barómetro", B: "Sismógrafo", C: "Termómetro" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 39,
        question: "¿En qué país se encuentra la ciudad de Petra?",
        options: { A: "Egipto", B: "Jordania", C: "Israel" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 40,
        question: "¿Quién fue el líder de la Revolución Cubana?",
        options: { A: "Che Guevara", B: "Fidel Castro", C: "Batista" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 41,
        question: "¿Cuál es el gas más abundante en la atmósfera terrestre?",
        options: { A: "Oxígeno", B: "Nitrógeno", C: "Dióxido de carbono" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 42,
        question: "¿Qué escritor escribió '1984'?",
        options: { A: "Aldous Huxley", B: "George Orwell", C: "Ray Bradbury" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 43,
        question: "¿Cuál es la capital de Japón?",
        options: { A: "Kioto", B: "Osaka", C: "Tokio" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 44,
        question: "¿Qué famoso discurso comenzó con 'Tengo un sueño'?",
        options: { A: "Nelson Mandela", B: "Martin Luther King", C: "Barack Obama" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 45,
        question: "¿Cuál es el número atómico del hidrógeno?",
        options: { A: "1", B: "2", C: "3" },
        correct_answer: "A",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 46,
        question: "¿Quién es el autor de 'El Principito'?",
        options: { A: "Antoine de Saint-Exupéry", B: "Jules Verne", C: "Victor Hugo" },
        correct_answer: "A",
        difficulty: "facil",
        category: "literatura",
    },
    {
        id: 47,
        question: "¿Cuál es el país más grande de Sudamérica?",
        options: { A: "Argentina", B: "Perú", C: "Brasil" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 48,
        question: "¿Qué civilización construyó Machu Picchu?",
        options: { A: "Azteca", B: "Maya", C: "Inca" },
        correct_answer: "C",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 49,
        question: "¿Cuál es el resultado de 15 + 27?",
        options: { A: "42", B: "32", C: "52" },
        correct_answer: "A",
        difficulty: "facil",
        category: "matematicas",
    },
    {
        id: 50,
        question: "¿Qué famoso cuadro de Leonardo da Vinci se encuentra en el Louvre?",
        options: { A: "La última cena", B: "La Mona Lisa", C: "La Gioconda" },
        correct_answer: "B",
        difficulty: "facil",
        category: "arte",
    },
    {
        id: 51,
        question: "¿Cuál es la capital de Argentina?",
        options: { A: "Buenos Aires", B: "Córdoba", C: "Rosario" },
        correct_answer: "A",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 52,
        question: "¿Qué artista pintó 'El grito'?",
        options: { A: "Vincent van Gogh", B: "Pablo Picasso", C: "Edvard Munch" },
        correct_answer: "C",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 53,
        question: "¿Cuál es el metal más caro del mundo?",
        options: { A: "Oro", B: "Platino", C: "Rodio" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 54,
        question: "¿En qué año cayó el Muro de Berlín?",
        options: { A: "1985", B: "1989", C: "1991" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 55,
        question: "¿Qué planeta es conocido como 'el planeta rojo'?",
        options: { A: "Venus", B: "Júpiter", C: "Marte" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 56,
        question: "¿Cuál es el país más grande del mundo por superficie?",
        options: { A: "China", B: "Canadá", C: "Rusia" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 57,
        question: "¿Qué escritor creó el personaje de Sherlock Holmes?",
        options: { A: "Charles Dickens", B: "Arthur Conan Doyle", C: "Agatha Christie" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 58,
        question: "¿Cuál es el hueso más pequeño del cuerpo humano?",
        options: { A: "Estribo", B: "Martillo", C: "Yunque" },
        correct_answer: "A",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 59,
        question: "¿Qué país ganó el primer Mundial de Fútbol en 1930?",
        options: { A: "Argentina", B: "Brasil", C: "Uruguay" },
        correct_answer: "C",
        difficulty: "media",
        category: "deportes",
    },
    {
        id: 60,
        question: "¿Cuál es el símbolo químico del oro?",
        options: { A: "Go", B: "Au", C: "Ag" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 61,
        question: "¿Qué famoso científico formuló las leyes del movimiento?",
        options: { A: "Albert Einstein", B: "Galileo Galilei", C: "Isaac Newton" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 62,
        question: "¿Cuál es el océano más pequeño del mundo?",
        options: { A: "Índico", B: "Ártico", C: "Antártico" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 63,
        question: "¿En qué país se encuentra la Torre Eiffel?",
        options: { A: "Italia", B: "Francia", C: "España" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 64,
        question: "¿Qué famoso compositor era sordo?",
        options: { A: "Mozart", B: "Bach", C: "Beethoven" },
        correct_answer: "C",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 65,
        question: "¿Cuál es el animal terrestre más rápido?",
        options: { A: "León", B: "Guepardo", C: "Leopardo" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 66,
        question: "¿Qué famoso líder indio promovió la resistencia no violenta?",
        options: { A: "Nehru", B: "Gandhi", C: "Tagore" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 67,
        question: "¿Cuál es el país con más habitantes del mundo?",
        options: { A: "India", B: "Estados Unidos", C: "China" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 68,
        question: "¿Qué planeta tiene anillos visibles desde la Tierra?",
        options: { A: "Júpiter", B: "Saturno", C: "Urano" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 69,
        question: "¿Qué escritor español escribió 'Don Quijote de la Mancha'?",
        options: { A: "Miguel de Cervantes", B: "Federico García Lorca", C: "Pío Baroja" },
        correct_answer: "A",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 70,
        question: "¿Cuál es la montaña más alta de África?",
        options: { A: "Monte Kenia", B: "Kilimanjaro", C: "Monte Stanley" },
        correct_answer: "B",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 71,
        question: "¿Qué pintor español es conocido por su etapa 'cubista'?",
        options: { A: "Salvador Dalí", B: "Joan Miró", C: "Pablo Picasso" },
        correct_answer: "C",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 72,
        question: "¿Qué elemento químico tiene el símbolo 'Na'?",
        options: { A: "Níquel", B: "Neón", C: "Sodio" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 73,
        question: "¿En qué continente se encuentra el desierto del Sahara?",
        options: { A: "Asia", B: "África", C: "América" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 74,
        question: "¿Qué científico descubrió la penicilina?",
        options: { A: "Marie Curie", B: "Alexander Fleming", C: "Louis Pasteur" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 75,
        question: "¿Cuál es el idioma oficial de Brasil?",
        options: { A: "Español", B: "Portugués", C: "Brasileño" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 76,
        question: "¿Qué famoso filósofo escribió 'El Príncipe'?",
        options: { A: "Platón", B: "Aristóteles", C: "Maquiavelo" },
        correct_answer: "C",
        difficulty: "media",
        category: "filosofia",
    },
    {
        id: 77,
        question: "¿Qué país tiene forma de bota?",
        options: { A: "Francia", B: "España", C: "Italia" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 78,
        question: "¿Cuál es el metal líquido a temperatura ambiente?",
        options: { A: "Plomo", B: "Mercurio", C: "Oro" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 79,
        question: "¿Qué famoso compositor austriaco era niño prodigio?",
        options: { A: "Beethoven", B: "Mozart", C: "Bach" },
        correct_answer: "B",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 80,
        question: "¿Qué país es el mayor productor de café en el mundo?",
        options: { A: "Colombia", B: "Vietnam", C: "Brasil" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 81,
        question: "¿Qué famoso físico formuló la teoría de la relatividad?",
        options: { A: "Isaac Newton", B: "Albert Einstein", C: "Stephen Hawking" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 82,
        question: "¿Cuál es el país más pequeño del mundo?",
        options: { A: "Mónaco", B: "San Marino", C: "Vaticano" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 83,
        question: "¿Qué famoso explorador llegó a América en 1492?",
        options: { A: "Vasco da Gama", B: "Fernando de Magallanes", C: "Cristóbal Colón" },
        correct_answer: "C",
        difficulty: "facil",
        category: "historia",
    },
    {
        id: 84,
        question: "¿Qué planeta es el más cercano al Sol?",
        options: { A: "Venus", B: "Tierra", C: "Mercurio" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 85,
        question: "¿Qué famoso científico desarrolló la teoría de la evolución?",
        options: { A: "Gregor Mendel", B: "Charles Darwin", C: "Louis Pasteur" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 86,
        question: "¿Qué país es conocido como 'la tierra del sol naciente'?",
        options: { A: "China", B: "Corea del Sur", C: "Japón" },
        correct_answer: "C",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 87,
        question: "¿Qué famoso artista pintó la 'Mona Lisa'?",
        options: { A: "Miguel Ángel", B: "Rafael", C: "Leonardo da Vinci" },
        correct_answer: "C",
        difficulty: "facil",
        category: "arte",
    },
    {
        id: 88,
        question: "¿Cuál es el hueso más largo del cuerpo humano?",
        options: { A: "Tibia", B: "Peroné", C: "Fémur" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 89,
        question: "¿Qué país ganó más Copas Mundiales de Fútbol?",
        options: { A: "Alemania", B: "Brasil", C: "Italia" },
        correct_answer: "B",
        difficulty: "media",
        category: "deportes",
    },
    {
        id: 90,
        question: "¿Qué famoso inventor desarrolló el bombillo eléctrico?",
        options: { A: "Nikola Tesla", B: "Thomas Edison", C: "Alexander Graham Bell" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 91,
        question: "¿Cuál es la capital de Canadá?",
        options: { A: "Toronto", B: "Montreal", C: "Ottawa" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 92,
        question: "¿Qué famoso compositor ruso escribió 'El lago de los cisnes'?",
        options: { A: "Tchaikovsky", B: "Stravinsky", C: "Shostakovich" },
        correct_answer: "A",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 93,
        question: "¿Qué elemento químico tiene el símbolo 'Fe'?",
        options: { A: "Flúor", B: "Francio", C: "Hierro" },
        correct_answer: "C",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 94,
        question: "¿Qué famoso líder sudafricano luchó contra el apartheid?",
        options: { A: "Desmond Tutu", B: "Nelson Mandela", C: "F.W. de Klerk" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 95,
        question: "¿Qué país es el mayor productor de petróleo en el mundo?",
        options: { A: "Arabia Saudita", B: "Rusia", C: "Estados Unidos" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 96,
        question: "¿Qué famoso pintor holandés cortó parte de su oreja?",
        options: { A: "Rembrandt", B: "Vincent van Gogh", C: "Johannes Vermeer" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 97,
        question: "¿Cuál es el país con más islas en el mundo?",
        options: { A: "Filipinas", B: "Indonesia", C: "Suecia" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 98,
        question: "¿Qué famoso científico propuso la ley de la gravitación universal?",
        options: { A: "Galileo Galilei", B: "Albert Einstein", C: "Isaac Newton" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 99,
        question: "¿Qué país tiene la bandera roja con una gran estrella amarilla?",
        options: { A: "China", B: "Vietnam", C: "Corea del Norte" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 100,
        question: "¿Qué famoso escritor ruso escribió 'Guerra y Paz'?",
        options: { A: "Fiódor Dostoyevski", B: "León Tolstói", C: "Antón Chéjov" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 101,
        question: "¿Qué famoso emperador romano construyó un muro en Britania?",
        options: { A: "Julio César", B: "Augusto", C: "Adriano" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "historia",
    },
    {
        id: 102,
        question: "¿Cuál es el metal más abundante en la corteza terrestre?",
        options: { A: "Hierro", B: "Aluminio", C: "Calcio" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 103,
        question: "¿Qué país europeo no tiene costa marítima?",
        options: { A: "Suiza", B: "Austria", C: "Todas las anteriores" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 104,
        question: "¿Qué pintor barroco español es conocido por sus 'Meninas'?",
        options: { A: "El Greco", B: "Diego Velázquez", C: "Francisco de Goya" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 105,
        question: "¿Cuál es el único mamífero capaz de volar?",
        options: { A: "Ardilla voladora", B: "Murciélago", C: "Lémur volador" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 106,
        question: "¿Qué famoso filósofo dijo 'Pienso, luego existo'?",
        options: { A: "Sócrates", B: "Platón", C: "Descartes" },
        correct_answer: "C",
        difficulty: "media",
        category: "filosofia",
    },
    {
        id: 107,
        question: "¿Qué país tiene la forma de una bota?",
        options: { A: "Grecia", B: "Italia", C: "España" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 108,
        question: "¿Cuál es el órgano más grande del cuerpo humano?",
        options: { A: "Cerebro", B: "Hígado", C: "Piel" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 109,
        question: "¿Qué famoso compositor era sordo cuando compuso su 9ª Sinfonía?",
        options: { A: "Mozart", B: "Bach", C: "Beethoven" },
        correct_answer: "C",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 110,
        question: "¿Qué ciudad es conocida como 'La Ciudad Eterna'?",
        options: { A: "Atenas", B: "Roma", C: "Jerusalén" },
        correct_answer: "B",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 111,
        question: "¿Qué elemento químico tiene el símbolo 'K'?",
        options: { A: "Kriptón", B: "Potasio", C: "Kalio" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 112,
        question: "¿Qué famoso líder indio fue asesinado en 1948?",
        options: { A: "Jawaharlal Nehru", B: "Indira Gandhi", C: "Mahatma Gandhi" },
        correct_answer: "C",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 113,
        question: "¿Qué país tiene la mayor cantidad de pirámides?",
        options: { A: "Egipto", B: "México", C: "Sudán" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 114,
        question: "¿Qué famoso científico descubrió la radiactividad?",
        options: { A: "Marie Curie", B: "Ernest Rutherford", C: "Henri Becquerel" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 115,
        question: "¿Qué famoso escritor inglés escribió 'Romeo y Julieta'?",
        options: { A: "Charles Dickens", B: "William Shakespeare", C: "Oscar Wilde" },
        correct_answer: "B",
        difficulty: "facil",
        category: "literatura",
    },
    {
        id: 116,
        question: "¿Qué país tiene la capital más alta del mundo?",
        options: { A: "Nepal", B: "Bolivia", C: "Ecuador" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 117,
        question: "¿Qué famoso artista pintó el techo de la Capilla Sixtina?",
        options: { A: "Leonardo da Vinci", B: "Rafael", C: "Miguel Ángel" },
        correct_answer: "C",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 118,
        question: "¿Qué planeta tiene el día más corto del sistema solar?",
        options: { A: "Mercurio", B: "Venus", C: "Júpiter" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 119,
        question: "¿Qué país fue dividido por el paralelo 38?",
        options: { A: "Vietnam", B: "Alemania", C: "Corea" },
        correct_answer: "C",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 120,
        question: "¿Qué famoso compositor austriaco compuso 'Pequeña serenata nocturna'?",
        options: { A: "Beethoven", B: "Mozart", C: "Haydn" },
        correct_answer: "B",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 121,
        question: "¿Qué país tiene la forma de un cuerno?",
        options: { A: "Somalia", B: "Etiopía", C: "Sudán" },
        correct_answer: "A",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 122,
        question: "¿Qué famoso científico formuló las tres leyes del movimiento planetario?",
        options: { A: "Galileo Galilei", B: "Johannes Kepler", C: "Isaac Newton" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 123,
        question: "¿Qué ciudad estadounidense es conocida como 'La Ciudad del Viento'?",
        options: { A: "Nueva York", B: "Los Ángeles", C: "Chicago" },
        correct_answer: "C",
        difficulty: "media",
        category: "geografia",
    },
    {
        id: 124,
        question: "¿Qué famoso escritor francés escribió 'Los miserables'?",
        options: { A: "Alexandre Dumas", B: "Victor Hugo", C: "Gustave Flaubert" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 125,
        question: "¿Qué país tiene la bandera más antigua aún en uso?",
        options: { A: "Reino Unido", B: "Dinamarca", C: "Suiza" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 126,
        question: "¿Qué famoso pintor holandés pintó 'La joven de la perla'?",
        options: { A: "Rembrandt", B: "Johannes Vermeer", C: "Frans Hals" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 127,
        question: "¿Qué elemento químico es el más ligero?",
        options: { A: "Helio", B: "Hidrógeno", C: "Litio" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 128,
        question: "¿Qué famoso líder ruso lideró la Revolución de Octubre?",
        options: { A: "León Trotsky", B: "Vladimir Lenin", C: "Joseph Stalin" },
        correct_answer: "B",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 129,
        question: "¿Qué país tiene más volcanes activos?",
        options: { A: "Japón", B: "Indonesia", C: "Chile" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 130,
        question: "¿Qué famoso científico propuso la teoría del Big Bang?",
        options: { A: "Albert Einstein", B: "Edwin Hubble", C: "Georges Lemaître" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "ciencia",
    },
    {
        id: 131,
        question: "¿Qué ciudad es conocida como 'La Perla del Adriático'?",
        options: { A: "Venecia", B: "Dubrovnik", C: "Split" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 132,
        question: "¿Qué famoso escritor ruso escribió 'Crimen y castigo'?",
        options: { A: "León Tolstói", B: "Fiódor Dostoyevski", C: "Antón Chéjov" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 133,
        question: "¿Qué elemento químico tiene el símbolo 'Ag'?",
        options: { A: "Oro", B: "Plata", C: "Argón" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 134,
        question: "¿Qué famoso líder sudafricano pasó 27 años en prisión?",
        options: { A: "Nelson Mandela", B: "Desmond Tutu", C: "F.W. de Klerk" },
        correct_answer: "A",
        difficulty: "media",
        category: "historia",
    },
    {
        id: 135,
        question: "¿Qué país tiene la mayor cantidad de lagos naturales?",
        options: { A: "Finlandia", B: "Canadá", C: "Rusia" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 136,
        question: "¿Qué famoso pintor español es conocido por sus relojes derretidos?",
        options: { A: "Pablo Picasso", B: "Salvador Dalí", C: "Joan Miró" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 137,
        question: "¿Qué planeta tiene los anillos más visibles?",
        options: { A: "Júpiter", B: "Saturno", C: "Urano" },
        correct_answer: "B",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 138,
        question: "¿Qué famoso filósofo griego fue maestro de Alejandro Magno?",
        options: { A: "Sócrates", B: "Platón", C: "Aristóteles" },
        correct_answer: "C",
        difficulty: "media",
        category: "filosofia",
    },
    {
        id: 139,
        question: "¿Qué país tiene la forma de un zapato?",
        options: { A: "Italia", B: "Grecia", C: "Croacia" },
        correct_answer: "A",
        difficulty: "facil",
        category: "geografia",
    },
    {
        id: 140,
        question: "¿Qué famoso compositor alemán compuso 'Para Elisa'?",
        options: { A: "Mozart", B: "Beethoven", C: "Bach" },
        correct_answer: "B",
        difficulty: "media",
        category: "musica",
    },
    {
        id: 141,
        question: "¿Qué elemento químico tiene el símbolo 'Hg'?",
        options: { A: "Hidrógeno", B: "Helio", C: "Mercurio" },
        correct_answer: "C",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 142,
        question: "¿Qué famoso líder egipcio nacionalizó el Canal de Suez en 1956?",
        options: { A: "Anwar Sadat", B: "Gamal Abdel Nasser", C: "Hosni Mubarak" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "historia",
    },
    {
        id: 143,
        question: "¿Qué país tiene la capital más al norte del mundo?",
        options: { A: "Finlandia", B: "Islandia", C: "Noruega" },
        correct_answer: "B",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 144,
        question: "¿Qué famoso científico descubrió los rayos X?",
        options: { A: "Marie Curie", B: "Wilhelm Röntgen", C: "Ernest Rutherford" },
        correct_answer: "B",
        difficulty: "media",
        category: "ciencia",
    },
    {
        id: 145,
        question: "¿Qué famoso escritor francés escribió 'El conde de Montecristo'?",
        options: { A: "Victor Hugo", B: "Alexandre Dumas", C: "Gustave Flaubert" },
        correct_answer: "B",
        difficulty: "media",
        category: "literatura",
    },
    {
        id: 146,
        question: "¿Qué país tiene la forma de un dragón?",
        options: { A: "Vietnam", B: "Tailandia", C: "Camboya" },
        correct_answer: "A",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 147,
        question: "¿Qué famoso pintor impresionista pintó 'Nenúfares'?",
        options: { A: "Vincent van Gogh", B: "Claude Monet", C: "Pierre-Auguste Renoir" },
        correct_answer: "B",
        difficulty: "media",
        category: "arte",
    },
    {
        id: 148,
        question: "¿Qué planeta es conocido como 'el planeta azul'?",
        options: { A: "Tierra", B: "Neptuno", C: "Urano" },
        correct_answer: "A",
        difficulty: "facil",
        category: "ciencia",
    },
    {
        id: 149,
        question: "¿Qué famoso filósofo escribió 'El contrato social'?",
        options: { A: "Voltaire", B: "Montesquieu", C: "Rousseau" },
        correct_answer: "C",
        difficulty: "dificil",
        category: "filosofia",
    },
    {
        id: 150,
        question: "¿Qué país tiene la forma de un cuerno de rinoceronte?",
        options: { A: "Somalia", B: "Etiopía", C: "Yemen" },
        correct_answer: "A",
        difficulty: "dificil",
        category: "geografia",
    },
    {
        id: 151,
        pregunta: "¿Cuál es el número romano que representa el 100?",
        opciones: { A: "L", B: "C", C: "D" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "matematicas",
    },
    {
        id: 152,
        pregunta: "¿Cuál es la raíz cuadrada de 144?",
        opciones: { A: "11", B: "12", C: "13" },
        respuesta_correcta: "B",
        dificultad: "media",
        categoria: "matematicas",
    },
    {
        id: 153,
        pregunta: "¿Cuál es el valor de π (pi) redondeado a dos decimales?",
        opciones: { A: "3.14", B: "3.41", C: "3.12" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "matematicas",
    },
    {
        id: 154,
        pregunta: "¿Cuál es el idioma más hablado en el mundo como lengua materna?",
        opciones: { A: "Inglés", B: "Chino mandarín", C: "Español" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "cultura",
    },
    {
        id: 155,
        pregunta: "¿Qué festividad mexicana se celebra el 2 de noviembre?",
        opciones: { A: "Día de Muertos", B: "Carnaval", C: "Día de la Independencia" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "cultura",
    },
    {
        id: 156,
        pregunta: "¿Cuál es el nombre del alfabeto utilizado en la antigua Mesopotamia?",
        opciones: { A: "Jeroglífico", B: "Cuneiforme", C: "Fenicio" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "cultura",
    },
    {
        id: 157,
        pregunta: "¿Cuántos jugadores tiene un equipo de fútbol en el campo?",
        opciones: { A: "9", B: "10", C: "11" },
        respuesta_correcta: "C",
        dificultad: "facil",
        categoria: "deportes",
    },
    {
        id: 158,
        pregunta: "¿En qué deporte se utiliza el término 'birdie'?",
        opciones: { A: "Tenis", B: "Golf", C: "Béisbol" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "deportes",
    },
    {
        id: 159,
        pregunta: "¿Quién compuso 'Las cuatro estaciones'?",
        opciones: { A: "Bach", B: "Vivaldi", C: "Mozart" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "musica",
    },
    {
        id: 160,
        pregunta: "¿Qué instrumento musical tiene 88 teclas?",
        opciones: { A: "Órgano", B: "Piano", C: "Acordeón" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "musica",
    },
    {
        id: 161,
        pregunta: "¿Quién escribió 'La República'?",
        opciones: { A: "Aristóteles", B: "Sócrates", C: "Platón" },
        respuesta_correcta: "C",
        dificultad: "facil",
        categoria: "filosofia",
    },
    {
        id: 162,
        pregunta: "¿Qué filósofo alemán escribió 'Así habló Zaratustra'?",
        opciones: { A: "Kant", B: "Nietzsche", C: "Hegel" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "filosofia",
    },
    {
        id: 163,
        pregunta: "¿Cuál fue el primer largometraje animado de Disney?",
        opciones: { A: "Pinocho", B: "Blancanieves", C: "Fantasía" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "arte",
    },
    {
        id: 164,
        pregunta: "¿Quién pintó 'El nacimiento de Venus'?",
        opciones: { A: "Botticelli", B: "Miguel Ángel", C: "Rafael" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "arte",
    },
    {
        id: 165,
        pregunta: "¿Quién escribió 'Orgullo y prejuicio'?",
        opciones: { A: "Jane Austen", B: "Emily Brontë", C: "Virginia Woolf" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "literatura",
    },
    {
        id: 166,
        pregunta: "¿Cuál es la capital de Nueva Zelanda?",
        opciones: { A: "Auckland", B: "Wellington", C: "Christchurch" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "geografia",
    },
    {
        id: 167,
        pregunta: "¿En qué año terminó la Segunda Guerra Mundial?",
        opciones: { A: "1943", B: "1945", C: "1947" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "historia",
    },
    {
        id: 168,
        pregunta: "¿Cuál es el único metal que se encuentra en estado líquido a temperatura ambiente?",
        opciones: { A: "Mercurio", B: "Plomo", C: "Estaño" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "ciencia",
    },
    {
        id: 169,
        pregunta: "¿Cuánto es 7 × 6?",
        opciones: { A: "42", B: "36", C: "48" },
        respuesta_correcta: "A",
        dificultad: "facil",
        categoria: "matematicas",
    },
    {
        id: 170,
        pregunta: "¿Cuál es el perímetro de un cuadrado de lado 5?",
        opciones: { A: "15", B: "20", C: "25" },
        respuesta_correcta: "B",
        dificultad: "media",
        categoria: "matematicas",
    },
    {
        id: 171,
        pregunta: "¿Cuál es el valor de 2 elevado a la 10?",
        opciones: { A: "512", B: "1024", C: "2048" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "matematicas",
    },
    {
        id: 172,
        pregunta: "¿Qué país es famoso por el carnaval de Río de Janeiro?",
        opciones: { A: "Argentina", B: "Brasil", C: "Colombia" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "cultura",
    },
    {
        id: 173,
        pregunta: "¿Cuál es la festividad japonesa conocida como 'Hanami'?",
        opciones: { A: "Ver flores de cerezo", B: "Año nuevo", C: "Festival de faroles" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "cultura",
    },
    {
        id: 174,
        pregunta: "¿Qué cultura antigua construyó las pirámides de Teotihuacán?",
        opciones: { A: "Maya", B: "Teotihuacana", C: "Olmeca" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "cultura",
    },
    {
        id: 175,
        pregunta: "¿Cuántos anillos tiene el símbolo olímpico?",
        opciones: { A: "4", B: "5", C: "6" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "deportes",
    },
    {
        id: 176,
        pregunta: "¿Cada cuántos años se celebran los Juegos Olímpicos de verano?",
        opciones: { A: "2", B: "3", C: "4" },
        respuesta_correcta: "C",
        dificultad: "media",
        categoria: "deportes",
    },
    {
        id: 177,
        pregunta: "¿En qué deporte se utiliza el término 'ace'?",
        opciones: { A: "Tenis", B: "Fútbol", C: "Baloncesto" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "deportes",
    },
    {
        id: 178,
        pregunta: "¿Qué instrumento tiene cuerdas y se toca con un arco?",
        opciones: { A: "Guitarra", B: "Violín", C: "Piano" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "musica",
    },
    {
        id: 179,
        pregunta: "¿Quién compuso la 'Sinfonía nº 5'?",
        opciones: { A: "Mozart", B: "Beethoven", C: "Bach" },
        respuesta_correcta: "B",
        dificultad: "media",
        categoria: "musica",
    },
    {
        id: 180,
        pregunta: "¿Qué compositor escribió 'La consagración de la primavera'?",
        opciones: { A: "Stravinsky", B: "Debussy", C: "Ravel" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "musica",
    },
    {
        id: 181,
        pregunta: "¿Quién fue el maestro de Platón?",
        opciones: { A: "Aristóteles", B: "Sócrates", C: "Pitágoras" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "filosofia",
    },
    {
        id: 182,
        pregunta: "¿Qué filósofo escribió 'Meditaciones metafísicas'?",
        opciones: { A: "Descartes", B: "Kant", C: "Hume" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "filosofia",
    },
    {
        id: 183,
        pregunta: "¿Qué filósofo griego fundó la escuela estoica?",
        opciones: { A: "Epicteto", B: "Zenón de Citio", C: "Marco Aurelio" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "filosofia",
    },
    {
        id: 184,
        pregunta: "¿Quién pintó 'La persistencia de la memoria'?",
        opciones: { A: "Salvador Dalí", B: "Pablo Picasso", C: "Joan Miró" },
        respuesta_correcta: "A",
        dificultad: "facil",
        categoria: "arte",
    },
    {
        id: 185,
        pregunta: "¿Qué artista pintó 'El grito'?",
        opciones: { A: "Munch", B: "Van Gogh", C: "Klimt" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "arte",
    },
    {
        id: 186,
        pregunta: "¿Quién esculpió 'El David'?",
        opciones: { A: "Donatello", B: "Miguel Ángel", C: "Bernini" },
        respuesta_correcta: "B",
        dificultad: "dificil",
        categoria: "arte",
    },
    {
        id: 187,
        pregunta: "¿Quién escribió 'Hamlet'?",
        opciones: { A: "Shakespeare", B: "Dickens", C: "Chaucer" },
        respuesta_correcta: "A",
        dificultad: "facil",
        categoria: "literatura",
    },
    {
        id: 188,
        pregunta: "¿Quién escribió 'La metamorfosis'?",
        opciones: { A: "Kafka", B: "Hesse", C: "Mann" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "literatura",
    },
    {
        id: 189,
        pregunta: "¿Quién escribió 'En busca del tiempo perdido'?",
        opciones: { A: "Proust", B: "Flaubert", C: "Balzac" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "literatura",
    },
    {
        id: 190,
        pregunta: "¿Cuál es la capital de Francia?",
        opciones: { A: "Lyon", B: "París", C: "Marsella" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "geografia",
    },
    {
        id: 191,
        pregunta: "¿Cuál es el país más pequeño de América del Sur?",
        opciones: { A: "Uruguay", B: "Surinam", C: "Ecuador" },
        respuesta_correcta: "B",
        dificultad: "media",
        categoria: "geografia",
    },
    {
        id: 192,
        pregunta: "¿Cuál es el lago más profundo del mundo?",
        opciones: { A: "Baikal", B: "Titicaca", C: "Mar Caspio" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "geografia",
    },
    {
        id: 193,
        pregunta: "¿Quién fue el primer emperador de Roma?",
        opciones: { A: "Julio César", B: "Augusto", C: "Nerón" },
        respuesta_correcta: "B",
        dificultad: "facil",
        categoria: "historia",
    },
    {
        id: 194,
        pregunta: "¿En qué año se descubrió América?",
        opciones: { A: "1492", B: "1498", C: "1500" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "historia",
    },
    {
        id: 195,
        pregunta: "¿Qué tratado puso fin a la Primera Guerra Mundial?",
        opciones: { A: "Versalles", B: "Tordesillas", C: "Westfalia" },
        respuesta_correcta: "A",
        dificultad: "dificil",
        categoria: "historia",
    },
    {
        id: 196,
        pregunta: "¿Cuál es el símbolo químico del agua?",
        opciones: { A: "H2O", B: "CO2", C: "O2" },
        respuesta_correcta: "A",
        dificultad: "facil",
        categoria: "ciencia",
    },
    {
        id: 197,
        pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?",
        opciones: { A: "206", B: "300", C: "150" },
        respuesta_correcta: "A",
        dificultad: "media",
        categoria: "ciencia",
    },
    {
        id: 198,
        pregunta: "¿Qué partícula subatómica tiene carga negativa?",
        opciones: { A: "Protón", B: "Neutrón", C: "Electrón" },
        respuesta_correcta: "C",
        dificultad: "dificil",
        categoria: "ciencia",
    },
];
